version: '2.3'

services:
  application-store:
    restart: always
    platform: linux/x86_64
    build:
      context: ../application-store
      dockerfile: Dockerfile
    environment:
      GIT_API_URL: "https://gitlab.com/api/v4/"
      GIT_ACCESS_TOKEN: "glpat-YkQovkQy1J8x2q6nXQst"
      SERVE_PORT: "8084"
    command: python3 main.py
    ports:
      - 8081:8084

  groups:
    restart: always
    platform: linux/x86_64
    build:
      context: ../groups
      dockerfile: Dockerfile
    environment:
      GIT_API_URL: "https://gitlab.com/api/v4/"
      GIT_ACCESS_TOKEN: "glpat-YkQovkQy1J8x2q6nXQst"
      SERVE_PORT: "8080"
    command: python3 main.py
    ports:
      - 8080:8080

volumes:
  postgresql-data:
  gitlab-data:
